### ISSUE TITLE
Getting this warning - Fetching config failed for service 3, error config fetching failed

### ISSUE THREAD

**Issue by tanalam2411** [rpscodes/3scale-OSSM-TravelDemo-Playbooks#4]
While following this blog - https://redhat-solution-patterns.github.io/solution-pattern-apim-servicemesh/comprehensive-service-architecture/03-demo.html, I ran this playbook and followed the rest of the instructions. 
At [Scenario 4](https://redhat-solution-patterns.github.io/solution-pattern-apim-servicemesh/comprehensive-service-architecture/03-demo.html#_scenario_4_securing_internal_api_access_inter_domain_traffic) it ask to provide 3Scale's Admin token in WasmPlugin CR.

```
 pluginConfig:
   api: v1
   system:
     name: system
     token: replace with access token
   ...  
   services:
     - id: '3'
       token: replace with service token
```

Even providing the 3Scale's admin token and service token, it keeps throwing this warning in `travel-agency travel-v1 istio-proxy` logs
```
warning envoy wasm wasm log: (root/1) 1644112912: Fetching config failed for service 3, error config fetching failed
```

I had tried to call both of these 3Scale APIs using the token provided in WasmPlugin CR and was getting a valid response with Service 3's config information. 
```
endpoint! { LIST, GET joining [ "/admin/api/services/", "/proxy/configs/", ".json" ] returning Configs }
endpoint! { LATEST, GET joining [ "/admin/api/services/", "/proxy/configs/", "/latest.json" ] returning ProxyConfig }
```

Can someone explain the exact use of the system token and service token and how we can debug Openshift Service Mesh filter. I was not getting much insight by just watching Istio's side car proxy logs and Openshift service mesh doesn't support istioctl.
